
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-18T12:05:45+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "5a32a1c75b5b15eddac88e4516310015f63f6799",
 "version": "1.9.25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
