on:
  push:
    branches:
#      - testing
      - main
    tags: "*"
  pull_request: null
name: Main Branch Builds
jobs:
  flatpak:
    name: Make Amulet Flatpak
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-24.08
      options:
        --privileged
    steps:
      - name: Build Flatpak
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.3
        with:
          bundle: amulet-x86_64.flatpak
          build-bundle: true
          repository-name: https://github.com/EvilSupahFly/Amulet-Flatpak/tree/main/io.github.evilsupahfly.amulet-flatpak
          manifest-path: io.github.evilsupahfly.amulet_flatpak.yaml
          cache-key: flatpak-builder-${{ github.sha }}
          verbose: true
          working-directory: ${{ github.workspace }}/sources
      - uses: actions/checkout@v4.2.2
      - name: Upload artifact
        uses: actions/upload-artifact@v4.4.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          name: amulet-x86_64.flatpak
          path: /__w/Amulet-Flatpak/Amulet-Flatpak/amulet-x86_64.flatpak
          overwrite: true
          compression-level: 0 # no compression
#      - name: Upload to Release Action
#        uses: Shopify/upload-to-release@v2.0.0
#        with:
#            name: amulet-x86_64.flatpak
#            path: /__w/Amulet-Flatpak/Amulet-Flatpak/amulet-x86_64.flatpak
#            content-type: application/vnd.flatpak
#            repo-token: ${{ github.token }}
