name: Main Branch Builds

on:
  push:
    branches:
      - main
    tags: "*"
  pull_request: null

jobs:
  flatpak:
    name: Make Amulet Flatpak
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Debug File Structure
        run: |
          echo "Root workspace files:"
          ls -R ${{ github.workspace }}
          echo "Sources folder files:"
          ls -R ${{ github.workspace }}/sources

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6.3
        with:
          manifest-path: io.github.evilsupahfly.amulet_flatpak.yaml
          verbose: true

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Automatic release for ${{ github.ref_name }}.
          draft: false
          prerelease: false
          generate_release_notes: true

      - name: Upload to Release
        uses: Shopify/upload-to-release@v2.0.0
        with:
          name: amulet-x86_64.flatpak
          path: ${{ github.workspace }}/amulet-x86_64.flatpak
          content-type: application/vnd.flatpak
          repo-token: ${{ secrets.GITHUB_TOKEN }}
