name: Main Branch Builds

on:
  push:
    branches:
      - main
    tags: "*"
  pull_request: null

jobs:
  flatpak:
    name: Make Amulet Flatpak
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      # Step 2: Debug file structure inside the Docker container
      - name: Debug File Structure After Checkout
        run: |
          echo "Listing files in sources directory inside the container:"
          ls -R /__w/Amulet-Flatpak/Amulet-Flatpak/sources

      # Step 3: Verify the file exists inside the Docker container
      - name: Verify File Exists After Checkout
        run: |
          if [ -f /__w/Amulet-Flatpak/Amulet-Flatpak/sources/packaging-25.0-py3-none-any.whl ]; then
            echo "File exists: packaging-25.0-py3-none-any.whl"
          else
            echo "File not found: packaging-25.0-py3-none-any.whl"
            exit 1
          fi

      # Step 4: Verify the checksum of the file inside the Docker container
      - name: Verify File Checksum After Checkout
        run: sha256sum /__w/Amulet-Flatpak/Amulet-Flatpak/sources/packaging-25.0-py3-none-any.whl

      # Step 5: Clear Flatpak Cache
      - name: Clear Flatpak Cache
        run: rm -rf ~/.cache/flatpak-builder

      # Step 6: Run the Flatpak Build
      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6.3
        with:
          manifest-path: io.github.evilsupahfly.amulet_flatpak.yaml
          verbose: true

      # Step 7: Debug Flatpak Logs if Build Fails
      - name: Debug Build Logs
        if: failure()
        run: |
          echo "Build failed. Capturing logs..."
          cat ~/.cache/flatpak-builder/logs/*
