name: Build and Release Flatpak

on:
  workflow_dispatch: {}

jobs:
  build-flatpak:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed so git tag checks work

      - name: Extract version from manifest
        id: get_version
        run: |
          version=$(grep -E '^#version:' io.github.evilsupahfly.amulet_flatpak.yaml | sed 's/#version:[[:space:]]*//')
          if [ -z "$version" ]; then
            echo "No version found in manifest"
            exit 1
          fi
          echo "version=$version" >> $GITHUB_ENV
          echo "Version detected: $version"

      - name: Check for existing Git tag
        run: |
          if git rev-parse "v${version}" >/dev/null 2>&1; then
            echo "Git tag v${version} already exists. Please bump the version in the manifest."
            exit 1
          fi

      - name: Set up Flatpak
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder xz-utils

      - name: Add Flathub remote
        run: |
          flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

      - name: Build Flatpak
        run: |
          mkdir -p build-dir
          flatpak-builder --force-clean --repo=repo build-dir io.github.evilsupahfly.amulet_flatpak.yaml

      - name: Create Flatpak bundle
        run: |
          flatpak build-bundle repo amulet_flatpak_${version}.flatpak io.github.evilsupahfly.amulet_flatpak

      - name: Upload Flatpak as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: amulet-flatpak
          path: amulet_flatpak_${{ env.version }}.flatpak

      - name: Create Git tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag -a "v${version}" -m "Release v${version}"
          git push origin "v${version}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.version }}
          name: Amulet Flatpak ${{ env.version }}
          files: amulet_flatpak_${{ env.version }}.flatpak
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
