name: Main Branch Builds

on:
  push:
    branches:
      - main
    tags: "*"
  pull_request: null

jobs:
  flatpak:
    name: Make Amulet Flatpak
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Verify File Checksum After Checkout
        run: sha256sum ${{ github.workspace }}/sources/packaging-25.0-py3-none-any.whl

      - name: Clear Flatpak Cache
        run: rm -rf ~/.cache/flatpak-builder

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6.3
        with:
          manifest-path: io.github.evilsupahfly.amulet_flatpak.yaml
          verbose: true

      - name: Debug File Checksum Inside Build
        run: sha256sum /path/to/packaging-25.0-py3-none-any.whl

      - name: Copy WHL File for Debugging
        run: cp /path/to/packaging-25.0-py3-none-any.whl ${{ github.workspace }}/debug-packaging-25.0-py3-none-any.whl

      - name: Verify Debug File Checksum
        run: sha256sum ${{ github.workspace }}/debug-packaging-25.0-py3-none-any.whl
