on:
  push:
    branches:
#      - testing
      - main
    tags: "*"
  pull_request: null
name: CI
jobs:
  flatpak:
    name: Make Amulet Flatpak
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-23.08
      options:
        --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: amulet-x86_64.flatpak
          build-bundle: true
          repository-name: https://github.com/EvilSupahFly/Amulet-Flatpak/tree/testing/io.github.evilsupahfly.amulet-flatpak
          manifest-path: ./io.github.evilsupahfly.amulet-flatpak.yaml
          cache-key: flatpak-builder-${{ github.sha }}
          verbose: true
      - name: Extract version from manifest
        id: get_version
        run: |
          VERSION=$(grep 'version:' io.github.evilsupahfly.amulet-flatpak.yaml | awk '{print $2}')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: /__w/Amulet-Flatpak/Amulet-Flatpak/amulet-x86_64.flatpak
          name: amulet-x86_64.flatpak
          path: /__w/Amulet-Flatpak/Amulet-Flatpak/amulet-x86_64.flatpak
          overwrite: true
          compression-level: 0 # no compression
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        run: |
          gh release upload ${{VERSION}} /__w/Amulet-Flatpak/Amulet-Flatpak/amulet-x86_64.flatpak
