name: Main Branch Builds

on:
  push:
    branches:
      - main
    tags: "*"
  pull_request: null

jobs:
  flatpak:
    name: Make Amulet Flatpak
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Debug File Structure
        run: |
          echo "Root workspace files:"
          ls -R ${{ github.workspace }}
          echo "Sources folder files:"
          ls -R ${{ github.workspace }}/sources

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6.3
        with:
          manifest-path: sources/io.github.evilsupahfly.amulet_flatpak.yaml
          verbose: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: amulet-x86_64.flatpak
          path: ${{ github.workspace }}/amulet-x86_64.flatpak
          overwrite: true
          compression-level: 0 # no compression
#      - name: Upload to Release Action
#        uses: Shopify/upload-to-release@v2.0.0
#        with:
#            name: amulet-x86_64.flatpak
#            path: /__w/Amulet-Flatpak/Amulet-Flatpak/amulet-x86_64.flatpak
#            content-type: application/vnd.flatpak
#            repo-token: ${{ github.token }}
