on:
  push:
    branches:
#      - testing
      - main
    tags: "*"
  pull_request: null
name: CI
jobs:
  flatpak:
    name: Make Amulet Flatpak
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-24.08
      options:
        --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: amulet-x86_64.flatpak
          build-bundle: true
          repository-name: https://github.com/EvilSupahFly/Amulet-Flatpak/tree/testing/io.github.evilsupahfly.amulet-flatpak
          manifest-path: ./io.github.evilsupahfly.amulet-flatpak.yml
          cache-key: flatpak-builder-${{ github.sha }}
          verbose: true
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          name: amulet-x86_64.flatpak
          path: /__w/Amulet-Flatpak/Amulet-Flatpak/amulet-x86_64.flatpak
          overwrite: true
          compression-level: 0 # no compression
