on:
  push:
    branches: [main]
  pull_request:
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-23.08
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: amulet.flatpak
        build-bundle: true
        repository-name: https://github.com/EvilSupahFly/Amulet-Flatpak/tree/main/amulet_flatpak_repo
        manifest-path: ./amulet.yml
        cache-key: flatpak-builder-${{ github.sha }}
