on:
  push:
    branches:
      - testing
#      - main
    tags: "*"
  pull_request: null
name: Snapshot Testing
jobs:
  flatpak:
    name: Make Amulet Flatpak
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-24.08
      options:
        --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: amulet-x86_64.flatpak
          build-bundle: true
          repository-name: https://github.com/EvilSupahFly/Amulet-Flatpak/tree/testing/io.github.evilsupahfly.amulet-flatpak
          manifest-path: ./io.github.evilsupahfly.amulet-flatpak.yml
          cache-key: flatpak-builder-${{ github.sha }}
          verbose: true
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          name: amulet-x86_64.flatpak
          path: /__w/Amulet-Flatpak/Amulet-Flatpak/amulet-x86_64.flatpak
          overwrite: true
          compression-level: 0 # no compression
      - name: Upload to Release Action
      # You may pin to the exact commit or the version.
      # uses: Shopify/upload-to-release@c77c9b3e5d288adaef98a7007bf92340ec6ce03b
        uses: Shopify/upload-to-release@v2.0.0
        with:
            name: amulet-x86_64.flatpak
            path: /__w/Amulet-Flatpak/Amulet-Flatpak/amulet-x86_64.flatpak
            content-type: application/vnd.flatpak
            repo-token: ${{ github.token }}
          
