#v12
name: Main Branch Builds

on:
  push:
    branches:
      - main
    tags: "*"
  pull_request: null

jobs:
  flatpak:
    name: Make Amulet Flatpak
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      # Step 2: Debug file structure and checksum after checkout
      - name: Log Environment Details
        run: |
          echo "Flatpak Builder Version:"
          flatpak-builder --version
          echo "Python Version:"
          python3 --version
          echo "File System Details:"
          df -h
      - name: Debug File Structure After Checkout
        run: |
          echo "Listing files in sources directory inside the container:"
          ls -R /__w/Amulet-Flatpak/Amulet-Flatpak/sources

      - name: Verify File Exists After Checkout
        run: |
          if [ -f /__w/Amulet-Flatpak/Amulet-Flatpak/sources/meson_python-0.17.1-py3-none-any.whl ]; then
            echo "File exists: meson_python-0.17.1-py3-none-any.whl"
          else
            echo "File not found: meson_python-0.17.1-py3-none-any.whl"
            exit 1
          fi

      - name: Verify File Checksum After Checkout
        run: sha256sum /__w/Amulet-Flatpak/Amulet-Flatpak/sources/meson_python-0.17.1-py3-none-any.whl

      # Step 3: Run the Flatpak Build with Interactive Debugging
      - name: Run Flatpak Build (Interactive)
        run: |
          mkdir -p /debug-container
          flatpak-builder --repo=repo --disable-rofiles-fuse --install-deps-from=flathub --force-clean --default-branch=master --arch=x86_64 --ccache --verbose flatpak_app flatpak-github-action-modified-io.github.evilsupahfly.amulet_flatpak.yaml || true
          echo "Flatpak build failed, but preserving container for debugging."
          echo "Copying build logs and environment for inspection."
          cp -r ~/.cache/flatpak-builder/logs/* /debug-container/logs || true
          cp -r /__w/Amulet-Flatpak/Amulet-Flatpak/sources /debug-container/sources || true
        continue-on-error: true

      # Step 4: Output Debug Information
      - name: Output Debug Information
        run: |
          echo "Capturing logs and environment details."
          ls -R /debug-container
          cat /debug-container/logs/* || echo "No logs available."
          sha256sum /debug-container/sources/meson_python-0.17.1-py3-none-any.whl || echo "No file available."
