name: Build PEX and Flatpak

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pex
      - name: Download wxPython wheel
        run: |
          mkdir -p wheels
          wget https://github.com/EvilSupahFly/ESF_Phoenix/releases/download/wxpython-4.2.3-cp312-cp312-linux_x86_64.whl/wxpython-4.2.3-cp312-cp312-linux_x86_64.whl -O wheels/wxpython-4.2.3-cp312-cp312-linux_x86_64.whl
      - name: Build PEX File
        run: |
          pex -o amulet.pex -r amulet_pex.txt -e amulet_map_editor --sh-boot --compress --find-links=./wheels -vv
      - name: Install Flatpak, flatpak-builder, and flatpak SDKs
        run: |
          sudo apt update
          sudo apt install -y flatpak flatpak-builder
          flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo
          flatpak install -y --user org.freedesktop.Platform/x86_64/24.08 org.freedesktop.Sdk/x86_64/24.08 org.freedesktop.Sdk.Extension.openjdk17/x86_64/24.08 org.freedesktop.Sdk.Extension.toolchain-i386/x86_64/24.08 org.gnome.Platform.Compat.i386/x86_64/48
      - name: Build amulet-x86_64.flatpak And Bundle
        run: |
          flatpak-builder -vvv --user --rebuild-on-sdk-change --force-clean --default-branch=master --arch=x86_64 --ccache --verbose --bundle-sources --repo="io.github.evilsupahfly.amulet_flatpak-repo" "io.github.evilsupahfly.amulet_flatpak-build-dir" "io.github.evilsupahfly.amulet_flatpak.yaml"
          flatpak build-bundle -vvv "io.github.evilsupahfly.amulet_flatpak-repo" amulet-x86_64.flatpak "io.github.evilsupahfly.amulet_flatpak"
      - name: Generate SHA256 checksums
        run: |
          sha256sum amulet.pex amulet-x86_64.flatpak > amulet-x86_64.flatpak.sha256
          cat amulet-x86_64.flatpak.sha256
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "Upload Artifacts"
          files: |
            amulet.pex
            amulet-x86_64.flatpak
      - name: Upload Flatpak to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Latest Build"
          tag_name: "latest"
          files: |
            amulet.pex
            amulet-x86_64.flatpak
            amulet-x86_64.flatpak.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

