---
on:
  push: 
    - branches: ["main", "token"]
    tags: "*"
    permissions: write-all
  pull_request: null
name: CI
jobs:
  flatpak:
    permissions: write-all
    name: Amulet Flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-23.08
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: amulet.flatpak
          build-bundle: true
          repository-name: https://github.com/EvilSupahFly/Amulet-Flatpak/tree/main/io.github.evilsupahfly.amulet-flatpak
          manifest-path: ./io.github.evilsupahfly.amulet-flatpak.yml
          cache-key: flatpak-builder-${{ github.sha }}
      - name: release
        uses: actions/create-release@latest
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: build artifacts
        run: make build-linux
      - name: upload linux artifact
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/amulet-x86_64.flatpak
          asset_name: amulet-x86_64.flatpak
          asset_content_type: application/vnd.flatpak
  print-token:
    permissions: write-all
    name: print-token
    environment: dev
    # needs: pre-pkr
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get registration token
        id: getRegToken
        run: |
          curl -X POST -H \"Accept: application/vnd.github.v3+json\"  -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/myprofile/myrepo/actions/runners/registration-token
