on:
  push:
#    branches:
#      - testing
#      - main
    tags: "*"
  pull_request: null
name: CI
jobs:
  flatpak:
    name: Make Amulet Flatpak
    runs-on: ubuntu-latest
    premissions:
      contents: write-all
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-23.08
      options:
        --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: amulet-x86_64.flatpak
          build-bundle: true
          repository-name: https://github.com/EvilSupahFly/Amulet-Flatpak/tree/testing/io.github.evilsupahfly.amulet-flatpak
          manifest-path: ./io.github.evilsupahfly.amulet-flatpak.yml
          cache-key: flatpak-builder-${{ github.sha }}
          upload-artifact: true
#      - name: release
#        uses: actions/create-release@latest
#        id: create_release
#        with:
#          draft: false
#          prerelease: true
#          release_name: Amulet Flatpak
#          tag_name: v0.10.35-beta
#        env:
#          GITHUB_TOKEN: ${{ github.token }}
#      - name: build artifacts
#        run: make build-linux
      - name: Upload artifact
        uses: actions/upload-artifact@v4
#        if: failure() || cancelled()
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: /__w/Amulet-Flatpak/Amulet-Flatpak/amulet-x86_64.flatpak
          name: amulet-x86_64.flatpak
          path: /__w/Amulet-Flatpak/Amulet-Flatpak/amulet-x86_64.flatpak
#          asset_content_type: application/vnd.flatpak
          overwrite: true
          compression-level: 0 # no compression
